//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.05 at 04:02:16 PM EST 
//


package edu.ncsu.csc573.project.common.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.ncsu.csc573.project.common.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.ncsu.csc573.project.common.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetType }
     * 
     */
    public GetType createGetType() {
        return new GetType();
    }

    /**
     * Create an instance of {@link SearchResponseType }
     * 
     */
    public SearchResponseType createSearchResponseType() {
        return new SearchResponseType();
    }

    /**
     * Create an instance of {@link LogoutParamsType }
     * 
     */
    public LogoutParamsType createLogoutParamsType() {
        return new LogoutParamsType();
    }

    /**
     * Create an instance of {@link JoinResponseTypeParams }
     * 
     */
    public JoinResponseTypeParams createJoinResponseTypeParams() {
        return new JoinResponseTypeParams();
    }

    /**
     * Create an instance of {@link ForgotPasswdParamsType }
     * 
     */
    public ForgotPasswdParamsType createForgotPasswdParamsType() {
        return new ForgotPasswdParamsType();
    }

    /**
     * Create an instance of {@link PutTypeParams }
     * 
     */
    public PutTypeParams createPutTypeParams() {
        return new PutTypeParams();
    }

    /**
     * Create an instance of {@link ForgotPWDResponseType }
     * 
     */
    public ForgotPWDResponseType createForgotPWDResponseType() {
        return new ForgotPWDResponseType();
    }

    /**
     * Create an instance of {@link LoginResponseType }
     * 
     */
    public LoginResponseType createLoginResponseType() {
        return new LoginResponseType();
    }

    /**
     * Create an instance of {@link PublishResponseTypeParams }
     * 
     */
    public PublishResponseTypeParams createPublishResponseTypeParams() {
        return new PublishResponseTypeParams();
    }

    /**
     * Create an instance of {@link CommandResponseType }
     * 
     */
    public CommandResponseType createCommandResponseType() {
        return new CommandResponseType();
    }

    /**
     * Create an instance of {@link LoginParamsType }
     * 
     */
    public LoginParamsType createLoginParamsType() {
        return new LoginParamsType();
    }

    /**
     * Create an instance of {@link PublishType }
     * 
     */
    public PublishType createPublishType() {
        return new PublishType();
    }

    /**
     * Create an instance of {@link PutResponseTypeParams }
     * 
     */
    public PutResponseTypeParams createPutResponseTypeParams() {
        return new PutResponseTypeParams();
    }

    /**
     * Create an instance of {@link PublishTypeParams }
     * 
     */
    public PublishTypeParams createPublishTypeParams() {
        return new PublishTypeParams();
    }

    /**
     * Create an instance of {@link GetResponseType }
     * 
     */
    public GetResponseType createGetResponseType() {
        return new GetResponseType();
    }

    /**
     * Create an instance of {@link DownloadUpdateType }
     * 
     */
    public DownloadUpdateType createDownloadUpdateType() {
        return new DownloadUpdateType();
    }

    /**
     * Create an instance of {@link JoinTypeParams }
     * 
     */
    public JoinTypeParams createJoinTypeParams() {
        return new JoinTypeParams();
    }

    /**
     * Create an instance of {@link LeaveResponseType }
     * 
     */
    public LeaveResponseType createLeaveResponseType() {
        return new LeaveResponseType();
    }

    /**
     * Create an instance of {@link PutType }
     * 
     */
    public PutType createPutType() {
        return new PutType();
    }

    /**
     * Create an instance of {@link FileDownloadType }
     * 
     */
    public FileDownloadType createFileDownloadType() {
        return new FileDownloadType();
    }

    /**
     * Create an instance of {@link InvalidResponseType }
     * 
     */
    public InvalidResponseType createInvalidResponseType() {
        return new InvalidResponseType();
    }

    /**
     * Create an instance of {@link ChangePasswordParamsType }
     * 
     */
    public ChangePasswordParamsType createChangePasswordParamsType() {
        return new ChangePasswordParamsType();
    }

    /**
     * Create an instance of {@link FileDownloadParams }
     * 
     */
    public FileDownloadParams createFileDownloadParams() {
        return new FileDownloadParams();
    }

    /**
     * Create an instance of {@link PutResponseType }
     * 
     */
    public PutResponseType createPutResponseType() {
        return new PutResponseType();
    }

    /**
     * Create an instance of {@link SearchType }
     * 
     */
    public SearchType createSearchType() {
        return new SearchType();
    }

    /**
     * Create an instance of {@link LogoutResponseType }
     * 
     */
    public LogoutResponseType createLogoutResponseType() {
        return new LogoutResponseType();
    }

    /**
     * Create an instance of {@link SearchTypeParams }
     * 
     */
    public SearchTypeParams createSearchTypeParams() {
        return new SearchTypeParams();
    }

    /**
     * Create an instance of {@link SearchResponseTypeParams }
     * 
     */
    public SearchResponseTypeParams createSearchResponseTypeParams() {
        return new SearchResponseTypeParams();
    }

    /**
     * Create an instance of {@link LogoutResponseParamsType }
     * 
     */
    public LogoutResponseParamsType createLogoutResponseParamsType() {
        return new LogoutResponseParamsType();
    }

    /**
     * Create an instance of {@link RegisterParamsType }
     * 
     */
    public RegisterParamsType createRegisterParamsType() {
        return new RegisterParamsType();
    }

    /**
     * Create an instance of {@link ChangePasswordResponseParamsType }
     * 
     */
    public ChangePasswordResponseParamsType createChangePasswordResponseParamsType() {
        return new ChangePasswordResponseParamsType();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link LeaveType }
     * 
     */
    public LeaveType createLeaveType() {
        return new LeaveType();
    }

    /**
     * Create an instance of {@link JoinType }
     * 
     */
    public JoinType createJoinType() {
        return new JoinType();
    }

    /**
     * Create an instance of {@link JoinResponseType }
     * 
     */
    public JoinResponseType createJoinResponseType() {
        return new JoinResponseType();
    }

    /**
     * Create an instance of {@link LoginResponseParamsType }
     * 
     */
    public LoginResponseParamsType createLoginResponseParamsType() {
        return new LoginResponseParamsType();
    }

    /**
     * Create an instance of {@link InvalidResponseTypeParams }
     * 
     */
    public InvalidResponseTypeParams createInvalidResponseTypeParams() {
        return new InvalidResponseTypeParams();
    }

    /**
     * Create an instance of {@link ForgotPasswdType }
     * 
     */
    public ForgotPasswdType createForgotPasswdType() {
        return new ForgotPasswdType();
    }

    /**
     * Create an instance of {@link MatchFileParamType }
     * 
     */
    public MatchFileParamType createMatchFileParamType() {
        return new MatchFileParamType();
    }

    /**
     * Create an instance of {@link LeaveTypeParams }
     * 
     */
    public LeaveTypeParams createLeaveTypeParams() {
        return new LeaveTypeParams();
    }

    /**
     * Create an instance of {@link LoginType }
     * 
     */
    public LoginType createLoginType() {
        return new LoginType();
    }

    /**
     * Create an instance of {@link TableParamType }
     * 
     */
    public TableParamType createTableParamType() {
        return new TableParamType();
    }

    /**
     * Create an instance of {@link DownloadUpdateParams }
     * 
     */
    public DownloadUpdateParams createDownloadUpdateParams() {
        return new DownloadUpdateParams();
    }

    /**
     * Create an instance of {@link DownloadFileParamType }
     * 
     */
    public DownloadFileParamType createDownloadFileParamType() {
        return new DownloadFileParamType();
    }

    /**
     * Create an instance of {@link ACKTypeParams }
     * 
     */
    public ACKTypeParams createACKTypeParams() {
        return new ACKTypeParams();
    }

    /**
     * Create an instance of {@link LeaveResponseTypeParams }
     * 
     */
    public LeaveResponseTypeParams createLeaveResponseTypeParams() {
        return new LeaveResponseTypeParams();
    }

    /**
     * Create an instance of {@link CommandRequestType }
     * 
     */
    public CommandRequestType createCommandRequestType() {
        return new CommandRequestType();
    }

    /**
     * Create an instance of {@link ACKType }
     * 
     */
    public ACKType createACKType() {
        return new ACKType();
    }

    /**
     * Create an instance of {@link ChangePasswordResponseType }
     * 
     */
    public ChangePasswordResponseType createChangePasswordResponseType() {
        return new ChangePasswordResponseType();
    }

    /**
     * Create an instance of {@link PublishResponseType }
     * 
     */
    public PublishResponseType createPublishResponseType() {
        return new PublishResponseType();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link GetTypeParams }
     * 
     */
    public GetTypeParams createGetTypeParams() {
        return new GetTypeParams();
    }

    /**
     * Create an instance of {@link GetResponseTypeParams }
     * 
     */
    public GetResponseTypeParams createGetResponseTypeParams() {
        return new GetResponseTypeParams();
    }

    /**
     * Create an instance of {@link ChangePasswordType }
     * 
     */
    public ChangePasswordType createChangePasswordType() {
        return new ChangePasswordType();
    }

    /**
     * Create an instance of {@link RegisterResponseType }
     * 
     */
    public RegisterResponseType createRegisterResponseType() {
        return new RegisterResponseType();
    }

    /**
     * Create an instance of {@link RegisterResponseParamsType }
     * 
     */
    public RegisterResponseParamsType createRegisterResponseParamsType() {
        return new RegisterResponseParamsType();
    }

    /**
     * Create an instance of {@link LogoutType }
     * 
     */
    public LogoutType createLogoutType() {
        return new LogoutType();
    }

    /**
     * Create an instance of {@link RegisterType }
     * 
     */
    public RegisterType createRegisterType() {
        return new RegisterType();
    }

    /**
     * Create an instance of {@link ForgotPWDResponseParamsType }
     * 
     */
    public ForgotPWDResponseParamsType createForgotPWDResponseParamsType() {
        return new ForgotPWDResponseParamsType();
    }

    /**
     * Create an instance of {@link FileParamType }
     * 
     */
    public FileParamType createFileParamType() {
        return new FileParamType();
    }

}
